# Generated by Django 3.0.2 on 2021-07-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20210716_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='img',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
