# Generated by Django 3.0.2 on 2021-07-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_todo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='img',
            field=models.CharField(max_length=500),
        ),
    ]
