# Generated by Django 3.0.2 on 2021-07-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_auto_20210717_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='img',
            new_name='foto',
        ),
    ]
