# Generated by Django 3.0.2 on 2021-07-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_auto_20210717_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='foto',
            field=models.CharField(max_length=1000),
        ),
    ]
